Updating the AuthZ scopes page for accuracy.
concur/developer.concur.com pull request #1485
Opened 2018-08-01 00:06 UTC by charlieconcur

This pull request makes the table markup simpler, clarifies some concepts and adds the APIs where found in the documentation.

2018-08-01 21:11 UTC, cliffstrom commented
Based on email thread, we don't want to put the API links on the same page, right?  Or do you think these changes are still good for developers to get a reference to the API?  Either way, we wouldn't be able to go live without more of the API links filled out.

2018-08-02 16:00 UTC, charlieconcur commented
I think you want scopes listed in the individual APIs and in a list form such as this one. I think these changes are good and should go live immediately even though we have some gaps to fill.

2018-08-06 21:26 UTC, cliffstrom requested changes
Let's wait to make these updates until we have more data.

2018-09-21 16:53 UTC, cliffstrom approved these changes

2018-09-21 18:01 UTC, merged