BUD-980 - updates to add budget managers and clean up formatting
concur/developer.concur.com pull request #1564
Opened 2018-09-21 22:09 UTC by jtbigwoo

2018-09-22 02:27 UTC, charlieconcur requested changes

2018-09-22 02:27 UTC, charlieconcur commented on src/api-reference/budget/budget-adjustments.md
> +[Terms of Use](/Terms-of-Use.html)
Remove this and we are good to go.

2018-09-22 02:27 UTC, charlieconcur commented on src/api-reference/budget/budget-adjustments.md
> +[Terms of Use](/Terms-of-Use.html)
This = Terms of Use

2018-09-24 13:59 UTC, jtbigwoo commented
Updated.  Also fixed some field names that I had missed in the previous commit.

2018-09-24 15:20 UTC, charlieconcur approved these changes

2018-09-24 15:20 UTC, merged