PurchseOrder V3 API documentation changes for new fields
concur/developer.concur.com pull request #1592
Opened 2018-09-25 14:10 UTC by harishrconcur

As part of V3 Purchase Order we introduced some changes. It is already live in Sep SU, this is to update the customer facing documentation.

Related development Jira - INV-28161

2018-09-25 15:25 UTC, prithvi-varla approved these changes

2018-09-26 17:21 UTC, retrosight commented
Test feedback from an account with Write privileges -- please ignore.

2018-09-26 17:56 UTC, sarraloew requested changes
The table formatting went a bit off with these changes. Also, on line 25, you have "Please use CES for batch updates." CES is an outdated term. Please replace it with the product name, which I'm guessing in this case is Concur Invoice. Thanks!

2018-09-26 17:56 UTC, sarraloew commented on src/api-reference/invoice/v3.purchase-order.markdown
> +---|---|---|---The purchase request number.
This change broke the table.

2018-09-26 17:56 UTC, sarraloew commented on src/api-reference/invoice/v3.purchase-order.markdown
> +
This change broke the table.

2018-09-26 21:43 UTC, harishrconcur commented
@sarraloew Thanks for catch I missed it. I have fixed your comments in 1c46fd24

2018-09-26 23:02 UTC, sarraloew approved these changes

2018-09-27 18:26 UTC, merged