Corrected email addresses, spacing, added SAP
concur/developer.concur.com pull request #1603
Opened 2018-09-28 18:14 UTC by RoAnnC1

Charlie please review.

2018-09-28 18:27 UTC, charlieconcur approved these changes
Looks good to me...!

2018-09-28 22:15 UTC, sarraloew approved these changes
Thank you!

2018-09-29 06:02 UTC, charlieconcur requested changes

2018-09-29 06:02 UTC, charlieconcur commented on src/api-guides/e-receipts.markdown
> +;The below Authentication Methods are available to obtain an access token. Password Grant or Authorization Grant or One-Time Password Grant is required for Certification:
Do we need the semicolon here?

2018-09-29 06:02 UTC, charlieconcur commented on src/api-guides/e-receipts.markdown
> +- [Password Grant](/api-reference/authentication/apidoc.html#password_grant) &ndash; Connect from the SAP Concur App Center.
While I agree that it probably looks a bit nicer to use the &ndash; -- in practical terms it just makes the docs harder to read and edit. I would move these back to plain dash.

2018-09-29 06:02 UTC, charlieconcur commented on src/api-guides/e-receipts.markdown
> +5. When your application receives the redirect call strip the **id** and **requestToken** values from the URI and use those on a Post request to the SAP Concur Authorization service to obtain the off
When noting key names or values use tick marks:

```
`id`
`requestToken`
`accessToken`
`refreshToken`
```

2018-09-29 06:02 UTC, charlieconcur commented on src/api-guides/e-receipts.markdown
> +5. When your application receives the redirect call strip the **id** and **requestToken** values from the URI and use those on a Post request to the SAP Concur Authorization service to obtain the off
Anytime you see underscores, convert them to dashes:

```
Before: #being_geo_aware
After:  #being-geo-aware
```

2018-09-29 06:02 UTC, charlieconcur commented on src/api-guides/e-receipts.markdown
> +You will need to be aware of the geolocation where the user exists in and make the call to the APIs correctly. If there is a case where you will not/do not know the user&#39;s geolocation, then you s
This: `&#39;` was leftover from someone who didn't know the difference between a tick mark and a single quote on their keyboard. Please convert all of these to single quotes when you find them.

2018-10-01 17:08 UTC, RoAnnC1 commented on src/api-guides/e-receipts.markdown
> +;The below Authentication Methods are available to obtain an access token. Password Grant or Authorization Grant or One-Time Password Grant is required for Certification:
No, sorry. Not sure what happened there.

2018-10-01 22:25 UTC, RoAnnC1 commented on src/api-guides/e-receipts.markdown
> +- [Password Grant](/api-reference/authentication/apidoc.html#password_grant) &ndash; Connect from the SAP Concur App Center.
Changed back to hyphen.

2018-10-01 22:25 UTC, RoAnnC1 commented on src/api-guides/e-receipts.markdown
> +5. When your application receives the redirect call strip the **id** and **requestToken** values from the URI and use those on a Post request to the SAP Concur Authorization service to obtain the off
Changed

2018-10-01 22:26 UTC, RoAnnC1 commented on src/api-guides/e-receipts.markdown
> +5. When your application receives the redirect call strip the **id** and **requestToken** values from the URI and use those on a Post request to the SAP Concur Authorization service to obtain the off
Changed

2018-10-01 22:26 UTC, RoAnnC1 commented on src/api-guides/e-receipts.markdown
> +You will need to be aware of the geolocation where the user exists in and make the call to the APIs correctly. If there is a case where you will not/do not know the user&#39;s geolocation, then you s
Fixed

2018-10-01 22:27 UTC, RoAnnC1 commented
Fixed changed Charlie requested

2018-10-01 22:29 UTC, closed without merging