Update various pages
concur/developer.concur.com pull request #1611
Opened 2018-10-01 22:31 UTC by RoAnnC1

2018-10-02 19:53 UTC, RoAnnC1 commented
Charlie do I need to do something else with this pull request?

2018-10-05 03:45 UTC, retrosight requested changes
See inline comments -- getting really close...!

2018-10-05 03:45 UTC, retrosight commented on src/api-guides/e-receipts.markdown
>      ![appflow_listing](/assets/img/api-guides/e-receipts/appflow_listing.png)
For images we should make everything within `[ ]` human readable sentences since these become the `< img alt="" >` attribute used by screen readers.

2018-10-05 03:45 UTC, retrosight commented on src/api-guides/e-receipts.markdown
> +- [Authorization Grant](/api-reference/authentication/apidoc.html#auth_grant) - Connect from the Partner App.
Remove the underscore and replace with hyphen in the URI -- I will make the corresponding anchor element change in the referred pages. Note: Changing the fragments (...#whatever) doesn't break the path before the fragment.

2018-10-05 03:45 UTC, retrosight commented on src/api-guides/e-receipts.markdown
> +- [Password Grant](/api-reference/authentication/apidoc.html#password_grant) - Connect from the SAP Concur App Center.
Replace the hyphen (`-`) for bulleted lists with asterisk (`*`) throughout.

2018-10-05 03:45 UTC, retrosight commented on src/api-guides/e-receipts.markdown
>  Example:   https://{partner_redirect_URI}?id=8568a4cd-8ffc-49d6-9417-be2d69aa075f&requestToken=5l85ae5a-426f-4d6f-8af4-08648c4b696b
If we can we should put the example on a separate line with triple ticks:

4. The redirect URI will contain an `id` and `requestToken` parameters. Example:

```
https://{partner_redirect_URI}?id=8568a4cd-8ffc-49d6-9417-be2d69aa075f&requestToken=5l85ae5a-426f-4d6f-8af4-08648c4b696b
```

5. When your application receives the redirect call strip the `id` and `requestToken` values

2018-10-05 03:45 UTC, retrosight commented on src/api-guides/e-receipts.markdown
> +6. Decode the `id\_token` to obtain the `sub` value and store this value as the user `id` (see [https://jwt.io](https://jwt.io)).
I'm not sure I understand the `\_` here -- I don't think it's necessary and the documentation this is based upon doesn't use it at all.

2018-10-05 03:45 UTC, retrosight commented on src/api-guides/e-receipts.markdown
>     - refresh\_token: (36 characters including dashes) valid for six months from the day and time issued.
These should be in single ticks as well. Basically if it is a `key` or a `value` in prose it should have ticks.

2018-10-05 03:45 UTC, retrosight commented on src/api-guides/e-receipts.markdown
> +   - Sub: (36 characters including dashes) user `id` value provided on the redirect URI.  The user `id` will be used to post receipts to the user's SAP Concur account.
I think `sub` should be lower case here but we should verify in the Auth docs.

2018-10-05 03:45 UTC, retrosight commented on src/api-guides/e-receipts.markdown
> +1. Partner App-User clicks on **Link to Concur** button within the Partner's website/mobile App.  Partner Web/Mobile Connection Example below:
Totally personal style: I prefer `website or mobile app` instead of `website/mobile app`.

2018-10-05 03:45 UTC, retrosight commented on src/api-guides/e-receipts.markdown
> +- SAP Concur generates a standard receipt for Partners who do not tender a receipt image.
Change 'tender' to 'provide' or 'post' or 'upload'...?

2018-10-05 03:45 UTC, retrosight commented on src/api-guides/e-receipts.markdown
> +4. You should store the Concur\_Correlation\_ID and the Location Link from the response headers even for successful responses, this will facilitate support efforts in case of a missing receipt from U
I believe it is `concur-correlationid`.

2018-10-05 03:45 UTC, retrosight commented on src/api-guides/e-receipts.markdown
> +2. A user's `refreshToken` is valid for six months.
Technically speaking, it is the `refreshToken` for the application, not the user. You can avoid the confusion altogether by saying 'A `refreshToken` is valid for six months.`

2018-10-05 03:45 UTC, retrosight commented on src/api-guides/e-receipts.markdown
> +4. If the user does not log in for six months his/her refresh token will expire and the user's Partner account and SAP Concur account will be de-linked.
Avoid `his/her` language and it is simply 'the refresh token will expire'.

2018-10-05 22:23 UTC, charlieconcur requested changes

2018-10-05 22:23 UTC, charlieconcur commented on src/api-reference/travel/itinerary-tmc-thirdparty/index.markdown
> +`DateModifiedUtc` |  The date that this trip was last modified, in UTC. Format: YYYY-MM-DDThh:mm:ss`Description` |  The trip description. Maximum length: 512 characters.
We seem to have merged two lines here?

2018-10-05 22:23 UTC, charlieconcur commented on src/api-guides/e-receipts.markdown
> +```Example:   https://{partner-redirect-URI}?id=8568a4cd-8ffc-49d6-9417-be2d69aa075f&requestToken=5l85ae5a-426f-4d6f-8af4-08648c4b696b```
Since we are getting wonkiness with the triple tick let's drop back to this Markdown using single ticks:

```
4. The redirect URI will contain an `id` and `requestToken` parameters. Example: `https://{partner-redirect-URI}?id=8568a4cd-8ffc-49d6-9417-be2d69aa075f&requestToken=5l85ae5a-426f-4d6f-8af4-08648c4b696b`
```

2018-10-05 22:23 UTC, charlieconcur commented on src/api-guides/e-receipts.markdown
> +    ![Example of what an App Center partner might display on their own site to allow their users to connect their user account at the partner with their account at Concur, using the web flow.](/asset
This is BEAUTIFUL accessibility awareness. Thank you.

2018-10-05 22:23 UTC, charlieconcur commented on src/api-guides/e-receipts.markdown
> +```Example: GET /oauth2/v0/authorize?client\_id={your-app-clientId}&redirect\_uri={partner_redirect_URI}&response\_type=code```
See note above about triple ticks.

2018-10-08 15:03 UTC, charlieconcur approved these changes

2018-10-08 15:03 UTC, merged