Remove notes to tech reviewers
concur/developer.concur.com pull request #1620
Opened 2018-10-08 20:01 UTC by RoAnnC1

Added SAP where needed
Updated links
Misc grammar updates

2018-10-11 20:21 UTC, sarraloew requested changes
I found one more outdated term, I'm adding it to my terms list.

2018-10-11 20:21 UTC, sarraloew commented on src/api-reference/travel/itinerary/itinerary.markdown
> +The Itinerary API can be used to programmatically access travel data such as trips and bookings in the SAP Concur Travel system. The SAP Concur Travel system uses this data to match and consolidate b
These two are just Concur Travel, as they refer to the product instead of the company.

2018-10-11 20:21 UTC, sarraloew commented on src/api-reference/travel/itinerary/itinerary.markdown
> +TripLink suppliers, travel management companies (TMCs), and SAP Concur partners can use the Itinerary API. The level of access to the data in the Concur Travel system on who is accessing it and the S
I think "data in the Concur Travel system on who is" should be "data in the Concur Travel system depends on who is"

2018-10-11 20:21 UTC, sarraloew commented on src/api-reference/travel/itinerary/itinerary.markdown
> +If you are a TMC or a SAP Concur partner developer who would like to start using this web service, please visit: [http://www.concur.com/en-us/connect-platform/suppliers][3] or contact the SAP Concur
Concur Connect Platform is an outdated term. Let's replace it with "SAP Partner Enablement Team"

2018-10-11 20:21 UTC, sarraloew commented on src/api-reference/travel/itinerary/itinerary.markdown
> +* If you are a TMC, third-party developer, or a TripLink supplier who would like to start using this web service, please visit: [http://www.concur.com/en-us/connect-platform/suppliers][3] or contact
Concur Connect Platform is an outdated term. Let's replace it with "SAP Partner Enablement Team"

2018-10-16 18:23 UTC, RoAnnC1 commented on src/api-reference/travel/itinerary/itinerary.markdown
> +If you are a TMC or a SAP Concur partner developer who would like to start using this web service, please visit: [http://www.concur.com/en-us/connect-platform/suppliers][3] or contact the SAP Concur
Fixed

2018-10-16 18:24 UTC, RoAnnC1 commented on src/api-reference/travel/itinerary/itinerary.markdown
> +* If you are a TMC, third-party developer, or a TripLink supplier who would like to start using this web service, please visit: [http://www.concur.com/en-us/connect-platform/suppliers][3] or contact
Fixed

2018-10-16 18:45 UTC, sarraloew approved these changes
Looks great, thanks!

2018-10-18 17:33 UTC, RoAnnC1 commented
Charlie, 
This is ready for review.

2018-10-18 19:33 UTC, merged