TVR-9203 Request API v4 documentation update
concur/developer.concur.com pull request #1649
Opened 2018-10-25 14:15 UTC by laurentlhermine

2018-10-25 16:18 UTC, charlieconcur requested changes
These changes are really good ones! We need to fix the whitespace issues in the JSON examples -- replacing tabs with two spaces. Otherwise the samples bleed off the page more than they should.

2018-10-26 09:07 UTC, cbobrie commented
Hi @laurentlhermine could you please check the tab space in the example file? I've checked them and they did not have any tab whitespaces but only two spaces, that's weird.
Appart from that it seems that we are ok with the rest of the changes 👍

2018-10-29 20:06 UTC, charlieconcur commented
You can see it really clearly in this JSON: https://github.com/concur/developer.concur.com/blob/4c0990eef12fe1d191db00d621b8d21a2554446a/src/api-reference/request/v4.examples.markdown#http-response-1

2018-11-06 17:17 UTC, charlieconcur approved these changes

2018-11-06 17:17 UTC, merged