Update v1.extracts.markdown
concur/developer.concur.com pull request #1653
Opened 2018-10-30 17:57 UTC by TimNiedConcur

I believe adding the capabilities section will remove any confusion on why or how to use the Extract API. 

Thank you, 
Tim Nied

2018-10-30 18:02 UTC, charlieconcur requested changes
Address the one piece of feedback and we are good to go.

2018-10-30 18:02 UTC, charlieconcur commented on src/api-reference/common/extracts/v1.extracts.markdown
> +https://{InstanceURL}/api/expense/extract/v1.0
We should wrap these with triple ticks to get them each on a line:

```
https://{InstanceURL}/api/expense/extract/v1.0
https://{InstanceURL}/api/expense/extract/v1.0/{DefinitionID}/job
https://{InstanceURL}/api/expense/extract/v1.0/{DefinitionID}/job/status
https://{InstanceURL}/api/expense/extract/v1.0/{DefinitionID}/job/{JobID}/file
```

2018-10-30 20:38 UTC, charlieconcur commented on src/api-reference/common/extracts/v1.extracts.markdown
> +https://{InstanceURL}/api/expense/extract/v1.0
I meant to wrap all four with tick marks as a code block.

2018-10-31 12:58 UTC, TimNiedConcur reviewed
Wrapping all URL's in triple tick marks.

2018-11-01 22:16 UTC, charlieconcur approved these changes

2018-11-01 22:16 UTC, merged