Pull Request for Travel Allowance API
concur/developer.concur.com pull request #1666
Opened 2018-11-06 08:24 UTC by UdayKumarNettem

2018-11-08 21:38 UTC, charlieconcur requested changes
See my notes.

2018-11-08 21:38 UTC, charlieconcur commented on src/api-reference/expense/travelallowance/travelallowance-days.md
> +![Image of Process_Flow](https://raw.githubusercontent.com/UdayKumarNettem/Image/master/Process_Flow.png)
This needs to move into the repository rather than stored in a personal location,

2018-11-08 21:38 UTC, charlieconcur commented on src/api-reference/expense/travelallowance/travelallowance-days.md
> +### Overview
Remove the 'Overview' section header.

2018-11-08 21:38 UTC, charlieconcur commented on src/api-reference/expense/travelallowance/travelallowance-days.md
> +This API is available only for Finland customers.
Put this on the same line with the word 'Limitations'.

2018-11-08 21:38 UTC, charlieconcur commented on src/api-reference/expense/travelallowance/travelallowance-days.md
> +|travelallowance.allowancedays.read|View the allowance days in an expense report|GET
Clean up the table formatting here -- it looks like you have the rest of them correct.

2018-11-08 21:38 UTC, charlieconcur commented on src/api-reference/expense/travelallowance/travelallowance-days.md
> +
No spaces between the request and header(s).

2018-11-08 21:38 UTC, charlieconcur commented on src/api-reference/expense/travelallowance/travelallowance-days.md
> +* See the GitHub topic [Creating and highlighting code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) for more information.
Should remove these three bullet points -- only here for document authors.

2018-11-09 05:07 UTC, closed without merging

2018-11-09 05:11 UTC, UdayKumarNettem commented
I have done the modifications and raise the new PR. Please have a look once
https://github.com/concur/developer.concur.com/pull/1687