Update partner support requirements
concur/developer.concur.com pull request #1735
Opened 2018-12-11 22:09 UTC by RoAnnC1

Simplified bullet nesting for readability.

2018-12-11 23:06 UTC, sarraloew requested changes
Small thing- please update Concur to SAP Concur. Thanks!

2018-12-11 23:14 UTC, RoAnnC1 commented
Fixed, thanks for pointing this out, saw there was an old email address too.

2018-12-13 20:36 UTC, sarraloew approved these changes

2018-12-13 20:36 UTC, sarraloew commented
:shipit:

2018-12-18 17:30 UTC, merged