USer Location API
concur/developer.concur.com pull request #1758
Opened 2019-01-15 09:47 UTC by KetanShrikhande

Document update

2019-01-16 17:08 UTC, charlieconcur requested changes
Good to go from my perspective with the requested changes.

2019-01-16 17:08 UTC, charlieconcur commented on src/api-reference/locate/userLocations.markdown
> +3. This API supports all Valid JWTs specifically client_credentials grant. Read the [Getting Started](/api-reference/authentication/getting-started.html) section of [Authentication API](/api-referenc
More properly stated:

This API supports all valid authorization tokens specifically those with the `client_credentials` grant.

2019-01-16 17:08 UTC, charlieconcur commented on src/api-reference/locate/userLocations.markdown
> +* When mobileCountryCode is non-blank it will validate the mobile number against that country’s market. It will accept the country letters (in this case JP) or the country code (in this case 81)
Be sure to tick the key names:

When `mobileCountryCode` is non-blank...

2019-01-17 17:43 UTC, KetanShrikhande commented
> Good to go from my perspective with the requested changes.

Thanks Charlie - I have updated the documentation per the review comments.

2019-01-17 18:40 UTC, charlieconcur approved these changes

2019-01-17 18:40 UTC, merged