Adding v4 documentation
concur/developer.concur.com pull request #1885
Opened 2019-03-25 08:34 UTC by KetanShrikhande

2019-03-25 17:10 UTC, sarraloew commented
Hi Ketan, the docs should be in the locate folder, with the version in the filesname like this: v4.user-locations.markdown. Also please add v1 and v4 to the page title. Thanks!

2019-03-26 08:25 UTC, KetanShrikhande commented
Hello! Made the changes per the review comments above.

2019-03-26 18:00 UTC, charlieconcur requested changes

2019-03-26 18:00 UTC, charlieconcur commented on src/api-reference/locate/v1.userLocations.markdown
> +title: User Locations V1 (Deprecating soon)
We shouldn't use 'deprecating soon' in the title. Use the official `includes` if you are going to deprecate AND we can create a new `includes` for this purpose if needed. See https://github.com/concur/developer.concur.com/blob/preview/src/_includes/deprecation-alert.html

2019-03-31 15:39 UTC, charlieconcur commented on src/api-reference/locate/v1.userLocations.markdown
> +title: User Locations V1 (Deprecating soon)
@sarraloew Maybe you'd like to chime in here?

2019-04-01 20:15 UTC, sarraloew commented on src/api-reference/locate/v1.userLocations.markdown
> +title: User Locations V1 (Deprecating soon)
I've asked for more clarification around whether the v1 API was ever used- we may be able to just remove that documentation without doing the full deprecation process.

2019-04-02 07:15 UTC, KetanShrikhande commented on src/api-reference/locate/v1.userLocations.markdown
> +title: User Locations V1 (Deprecating soon)
Thanks! No problems I will wait for the direction forward.

2019-04-09 17:31 UTC, sarraloew commented
I emailed the PM again, if I don't get a response soon we can publish this PR and handle the v1 deprecation separately.

2019-04-11 15:49 UTC, sarraloew commented on src/api-reference/locate/v1.userLocations.markdown
> +title: User Locations V1 (Deprecating soon)
One client is still using v1, so for now, remove the Deprecating soon text, and I'll connect with the PM on the official deprecation process.

2019-04-23 17:48 UTC, sarraloew commented
@KetanShrikhande Please remove the (Deprecating Soon) from v1, then we can merge this PR. Thanks!

2019-04-24 16:21 UTC, charlieconcur approved these changes

2019-04-24 16:22 UTC, charlieconcur commented on src/api-reference/locate/v1.userLocations.markdown
> +title: User Locations V1 (Deprecating soon)
I removed it for @KetanShrikhande.

2019-04-24 16:22 UTC, charlieconcur commented
:shipit:

2019-04-25 21:05 UTC, charlieconcur commented
@sarraloew I removed the `(Deprecating Soon)` on behalf of @KetanShrikhande. This one is ready to be merged.

2019-04-30 18:39 UTC, merged