Clarify Authentication Documentation
concur/developer.concur.com pull request #1905
Opened 2019-04-01 20:42 UTC by haydenlam

- Optional Scope Parameter
- Expected Behavior of Refresh Tokens

2019-04-01 21:05 UTC, charlieconcur requested changes

2019-04-01 21:05 UTC, charlieconcur commented on src/api-reference/authentication/apidoc.markdown
> +`scope`|`string` | | **Optional** The client applications list of scopes
```suggestion
`scope`|`string` |-| **Optional** The client applications list of scopes
```
We should denote an intentional blank cell with use of the `-`.

I would prefer we clear up the whitespace in the table as well.

2019-04-03 16:31 UTC, haydenlam commented
@charlieconcur The rest of the blank cells have been filled in.
Thanks

2019-04-03 16:50 UTC, charlieconcur approved these changes

2019-04-03 16:51 UTC, charlieconcur commented
:shipit:

2019-04-04 18:01 UTC, merged