Updates to API Explorer and User pages
concur/developer.concur.com pull request #1913
Opened 2019-04-03 18:09 UTC by RoAnnC1

Update API Explorer with current info.
Clarify note on User page, minor updates to spacing, heading title caps, etc.

2019-04-03 19:57 UTC, charlieconcur requested changes

2019-04-03 19:57 UTC, charlieconcur commented on src/api-reference/user/index.markdown
> +`loginID`|`string` | | The URL-encoded SAP Concur login of the user. Optional.
We need to clean up whitespace and make sure to denote empty cells intentionally with `|-|`.

2019-04-03 20:56 UTC, RoAnnC1 commented
Fixed

2019-04-03 21:33 UTC, sarraloew requested changes

2019-04-03 21:33 UTC, sarraloew commented on src/api-explorer/index.markdown
> +* **US**: https://us.api.concursolutions.com/api/{version}
These URLs should not end with /api/{version} as the new v4 URLs don't use that format.

2019-04-04 16:21 UTC, charlieconcur approved these changes

2019-04-04 16:22 UTC, charlieconcur commented on src/api-reference/user/index.markdown
> +`loginID`|`string` | | The URL-encoded SAP Concur login of the user. Optional.
Excellent, thanks.

2019-04-05 19:46 UTC, sarraloew commented
:shipit:

2019-04-05 19:46 UTC, sarraloew approved these changes

2019-04-05 19:46 UTC, merged