Updates Invoice docs with new terminology standards
concur/developer.concur.com pull request #1929
Opened 2019-04-08 19:40 UTC by jonikamelcher

2019-04-09 16:59 UTC, sarraloew requested changes

2019-04-09 16:59 UTC, sarraloew commented on src/api-reference/invoice/v3.payment-request-digest.markdown
>    - /api-reference/invoice/payment-request-digest.html
Need to update the title also.

2019-04-09 16:59 UTC, sarraloew commented on src/api-reference/invoice/v3.payment-request.markdown
>    - /api-reference/invoice/payment-request.html
Another title update

2019-04-09 16:59 UTC, sarraloew commented on src/api-reference/invoice/v3.payment-request.markdown
> +`CurrencyCode`|`string`|-|The 3-letter ISO 4217 currency code for the expense report currency. Examples: `USD` - US dollars; `BRL` - Brazilian real; `CAD` - Canadian dollar; `CHF` - Swiss franc; `EUR
should be invoice currency rather than expense report.

2019-04-09 21:46 UTC, sarraloew approved these changes

2019-04-09 21:46 UTC, sarraloew commented
:shipit:

2019-04-10 20:21 UTC, charlieconcur commented
:shipit:

2019-04-11 15:47 UTC, merged