Sign in with Concur for Enterprise Applications
concur/developer.concur.com pull request #1966
Opened 2019-04-22 21:15 UTC by brittnwestSAP

Describing enterprise application integrations in more detail. Providing guidelines for email verification for companies using email address as a unique identifier (not unique in Concur so requires verification before first sign in).

2019-04-22 21:33 UTC, charlieconcur requested changes
Do not use underscores (`_`) in file names -- use a dash instead (`-`).

2019-04-22 22:28 UTC, brittnwestSAP commented
updated new files and migrated old to dashes rather than underscore. Also changed full path to use dash - this is currently in pre-release and only affects 2 partners (whom I will notify specifically of the path change). Added pre-release header as well.

2019-04-23 15:05 UTC, charlieconcur approved these changes

2019-04-23 15:05 UTC, charlieconcur commented
:shipit:

2019-04-23 17:54 UTC, merged