EXP-28048: adding api sec documentation as first iteration for Financial Integration service
concur/developer.concur.com pull request #1992
Opened 2019-05-21 18:46 UTC by srikanthbabu133

adding api sec documentation as first iteration for Financial Integration service

@sarraloew

2019-05-21 18:52 UTC, sarraloew commented
Hi Srikanth, I ran this JSON through the swagger editor at https://editor.swagger.io/ and it has 6 errors, please review and fix those.

2019-05-21 23:50 UTC, sarraloew commented on src/api-explorer/v4-0/FinancialIntegrationService.swagger2.json
> +    "termsOfService": "http://terms-of-service.url",
remove the termsOfService, contact, and license objects, we don't use them.

2019-05-22 23:30 UTC, sarraloew commented
Sent a message to @srikanthbabu133 about request parameters not matching the markdown. The markdown is currently under review so if need be we can wait until the markdown is reviewed before doing the swagger cross-check.

2019-06-04 23:36 UTC, sarraloew requested changes

2019-06-04 23:36 UTC, sarraloew commented on src/api-explorer/v4-0/FinancialIntegrationService.swagger2.json
> +  "basePath": "/financialintegration",
We're not displaying the basePath value anywhere, so please empty this out and include it in the URL for each resource.

2019-06-04 23:36 UTC, sarraloew commented on src/api-explorer/v4-0/FinancialIntegrationService.swagger2.json
> +    "PublishedPurgeMessage": {
This model doesn't appear anywhere in the markdown- is it used?

2019-06-04 23:36 UTC, sarraloew commented on src/api-explorer/v4-0/FinancialIntegrationService.swagger2.json
> +    "PublishedMessage": {
This model doesn't appear anywhere in the markdown- is it used?

2019-06-04 23:36 UTC, sarraloew commented on src/api-explorer/v4-0/FinancialIntegrationService.swagger2.json
> +    "Facts": {
This model doesn't appear anywhere in the markdown- is it used?

2019-06-04 23:36 UTC, sarraloew commented on src/api-explorer/v4-0/FinancialIntegrationService.swagger2.json
> +    "DocumentRefreshQueueResponseItem": {
This model doesn't appear anywhere in the markdown- is it used?

2019-06-04 23:36 UTC, sarraloew commented on src/api-explorer/v4-0/FinancialIntegrationService.swagger2.json
> +    "Collection.Resource.FIDocument": {
This model is empty- shouldn't it link to Resource.FIDocument?

2019-06-06 23:31 UTC, sarraloew requested changes

2019-06-06 23:31 UTC, sarraloew commented on src/api-explorer/v4-0/FinancialIntegrationService.swagger2.json
> +        ],
The markdown includes a payload for this request, please add it here.

2019-06-06 23:31 UTC, sarraloew commented on src/api-explorer/v4-0/FinancialIntegrationService.swagger2.json
> +                "$ref": "#/definitions/PostingConfirmationResponseItem"
Should this be the PaymentConfirmationResponseItem instead?

2019-06-18 22:50 UTC, sarraloew commented on src/api-explorer/v4-0/FinancialIntegrationService.swagger2.json
> +                "$ref": "#/definitions/AcknowledgeResponseItem"
The markdown lists an item called AcknowledgeResponse, an array that contains multiple AcknowledgeResponseItem objects. The swagger only lists AcknowledgeResponseItem, which is correct?

2019-06-20 23:39 UTC, sarraloew requested changes

2019-06-20 23:39 UTC, sarraloew commented on src/api-explorer/v4-0/FinancialIntegrationService.swagger2.json
> +    "NotificationReceivedResponseItem": {
This model doesn't appear in the markdown, is it in use?

2019-06-20 23:39 UTC, sarraloew commented on src/api-explorer/v4-0/FinancialIntegrationService.swagger2.json
> +    "FiDocumentResponse": {
This model isn't used anywhere in the markdown, is it in use?

2019-06-21 19:11 UTC, srikanthbabu133 commented
@sarraloew please review, addressed your latest comments and updated the file with all changes.

2019-06-25 22:50 UTC, sarraloew commented
Sent question to Tuan and Srikanth about the messageLanguage supported values.

2019-06-26 23:44 UTC, sarraloew approved these changes

2019-06-26 23:45 UTC, sarraloew commented
:shipit:

2019-06-27 16:15 UTC, merged