Document Concur Request v4 cash advance & exception endpoints
concur/developer.concur.com pull request #2209
Opened 2019-12-19 15:04 UTC by laurentlhermine

+ Various enhancements and corrections

2020-01-03 00:20 UTC, sarraloew requested changes
I've got a few text edits and one question. Thanks!

2020-01-03 00:20 UTC, sarraloew commented on src/api-reference/request/v4.endpoints.request-resources.markdown
> +view|query|string|Name of the perimeter defining the Requests to get.<br>Possible values:<br>`ALL`: Get all existing Requests for a user (relevant only for the traveler);<br>`ACTIVE`Get all active Re
A few text edits, also is there a reason to not alphabetize these values? 
"perimeter" should be "parameter"
PENDING: Does pending mean submitted but not yet approved? or not yet final approved (could have some approvals but not all required approvals)? Please clarify.
CANCELED "close/not closed" should be "closed/not closed"
PENDINGPROPOSAL has an extra "step"
PROPOSALAPPROVED and PROPOSALCANCELLED should also have definitions.

2020-01-03 00:20 UTC, sarraloew commented on src/api-reference/request/v4.endpoints.schemas.markdown
> +approver|object|[Employee](#schema-employee)|The approver to whom the Request was sent to
Remove the final "to"

2020-01-03 00:20 UTC, sarraloew commented on src/api-reference/request/v4.endpoints.schemas.markdown
> +requestDate|timestamp|[RFC 3339] yyyy-MM-dd'T'HH:mm:ss.SSS|The date the cash advance was submitted (last submit date in case of recall))
remove extra parentheses

2020-01-03 08:56 UTC, quancheng-zhao commented
src/api-reference/request/v4.endpoints.schemas.markdown: in CustomField schema definition, listItemId is an old value and it needs to be removed.

2020-01-08 08:27 UTC, quancheng-zhao commented on src/api-reference/request/v4.endpoints.cashadvance-resources.markdown
> +## <a name="get-request-cash-advance-resource"></a>Get the content of an existing cash advances
Get the content of an existing cash advance

2020-01-08 09:38 UTC, quancheng-zhao commented
v4.endpoints.request-resources.markdown: GET {datacenter}/travelrequest/v4/requests/{requestUuid}/comments doesn't have userId as parameter

2020-01-08 10:09 UTC, quancheng-zhao commented on src/api-reference/request/v4.endpoints.schemas.markdown
> +source|array|[Exception source](#schema-exceptionsource)|The source that has raised the exception
Missing an attribute "parameters"? (Parameters for the messages of the exception)

2020-01-08 10:24 UTC, quancheng-zhao commented
Expected Expense Resource's description updates to "Manage expected expenses attached to a Request"

2020-01-08 20:52 UTC, sarraloew approved these changes

2020-01-08 20:52 UTC, sarraloew commented on src/api-reference/request/v4.endpoints.schemas.markdown
> +href|string||[RFC 3986]|Hyperlink to the resource
This line has an extra pipe. Also the swagger doc has additional information about this field that we should have here too: Will be empty if source is ALLOCATION or CASH_ADVANCE.

2020-01-08 20:52 UTC, sarraloew commented on src/api-reference/request/v4.endpoints.schemas.markdown
> +approver|object|[Employee](#schema-employee)|The approver to whom the Request was sent to
Also the swagger has this additional information, let's add it here too: Null when Request is in an approval status different from SUBMITTED

2020-01-08 20:52 UTC, sarraloew commented on src/api-reference/request/v4.endpoints.schemas.markdown
> +highestExceptionLevel|string|-|The highest level of exception contained in this Request. <br>Possible values: `WARNING`, `ERROR`
The swagger file includes NONE as a possible value for highestExceptionLevel- which is correct?

2020-01-08 20:54 UTC, merged