Add Field Definition Id as a required field to save cost tracking fields
concur/developer.concur.com pull request #2224
Opened 2020-01-16 19:16 UTC by elankumaranrk

Add Field Definition Id as a required field (replacing code) to save cost tracking fields during budget save.

2020-01-16 19:47 UTC, ledbutter approved these changes

2020-01-16 23:47 UTC, MarcBell-SAP requested changes

2020-01-16 23:47 UTC, MarcBell-SAP commented on src/api-explorer/v4-0/Budget.swagger2.json
> +        "fieldDefinitionId":{"type":"string"},
```suggestion
"fieldDefinitionId": { "type": "string" },
```

2020-01-21 18:28 UTC, MarcBell-SAP commented
:ship it:

2020-01-21 18:29 UTC, MarcBell-SAP commented
:shipit:

2020-01-21 18:29 UTC, merged