Provisioning swagger document
concur/developer.concur.com pull request #2231
Opened 2020-01-21 18:33 UTC by mvahlsing98117

File name change
File has been updated and tested.

2020-02-20 22:51 UTC, MarcBell-SAP requested changes

2020-02-20 22:51 UTC, MarcBell-SAP commented on swagger/draft/provisioning_swagger.json
> +    },
This object is never used. Please remove this from the document.

2020-02-20 22:51 UTC, MarcBell-SAP commented on swagger/draft/provisioning_swagger.json
> +        },
This object requires an items property because it's an array. See https://swagger.io/docs/specification/data-models/data-types/#array for reference.

2020-02-26 16:20 UTC, jonikamelcher commented
:shipit:

2020-02-26 16:20 UTC, merged