Adding clarifications to HS2 walkthrough/faq and improving sample XML.
concur/developer.concur.com pull request #2820
Opened 2021-08-11 21:01 UTC by rlee-sap

2021-08-12 17:23 UTC, stuart-ng-van approved these changes

2021-08-17 21:47 UTC, MarcBell-SAP requested changes
@rlee-sap Review and approve. Then I can merge it.

2021-08-17 21:47 UTC, MarcBell-SAP commented on src/api-guides/travel/hotelservice2/faq.markdown
> +A: The rate description is made up of the RateDescription, RatePlanDescription, RoomDescription, and MealsIncluded (breakfast) from the Availability response.
```suggestion
A: The rate description is made up of the `RateDescription`, `RatePlanDescription`, `RoomDescription`, and `MealsIncluded` (breakfast) from the Availability response.
```

2021-08-17 21:47 UTC, MarcBell-SAP commented on src/api-guides/travel/hotelservice2/faq.markdown
> +A: The text is generated using the content from Availability (or RateDetails when used). Including the following:
```suggestion
A: The text is generated using the content from Availability (or `RateDetails` when used). Including the following:
```

2021-08-17 21:47 UTC, MarcBell-SAP commented on src/api-guides/travel/hotelservice2/hotel-shop-book-cancel.markdown
> +    Out of 100 returned hotels in the response from the Hotel Supplier, the response may contain 10 Most Preferred hotels within the 30 mile radius, 10 Preferred within the 30 mile radius, and 10 Les
```suggestion
    Out of 100 returned hotels in the response from the Hotel Supplier, the response may contain the 10 `most_preferred` hotels within a 30 mile radius, the 10 `preferred` hotels within a 30 mile radius, and the 10 `less_preferred` hotels within a 30 mile radius. The remaining 70 hotels would be `not_preferred` hotels within a 5 mile radius. Note: The preference level is defined by the `HotelPreference` element in the TPA_Extensions, which is outlined in Search.
```

2021-08-17 21:47 UTC, MarcBell-SAP commented on src/api-guides/travel/hotelservice2/hotel-shop-book-cancel.markdown
> +    Please refer to the [FAQ](./faq.html#hotel-descriptive-info) for additional information regarding HotelDescriptiveInfo.
```suggestion
    Please refer to the [FAQ](./faq.html#hotel-descriptive-info) for additional information regarding `HotelDescriptiveInfo`.
```

2021-08-17 21:47 UTC, MarcBell-SAP commented on src/api-guides/travel/hotelservice2/hotel-shop-book-cancel.markdown
> +    Please refer to the [FAQ](./faq.html#availability) for additional information regarding RateDetails.
```suggestion
    Please refer to the [FAQ](./faq.html#availability) for additional information regarding `RateDetails`.
```

2021-08-17 21:47 UTC, MarcBell-SAP commented on src/api-guides/travel/hotelservice2/hotel-shop-book-cancel.markdown
> +    Please refer to the [FAQ](./faq.html#read-itinerary) for additional information regarding ReadItinerary.
```suggestion
    Please refer to the [FAQ](./faq.html#read-itinerary) for additional information regarding `ReadItinerary`.
```

2021-08-17 22:06 UTC, MarcBell-SAP commented
:shipit:

2021-08-17 22:12 UTC, MarcBell-SAP approved these changes

2021-08-17 22:12 UTC, merged